// WARNING: THIS CODE IS AUTO-GENERATED BY postgres-typescript. ANY MANUAL EDITS WILL BE OVERWRITTEN WITHOUT WARNING
/* tslint:disable */
import { Moment } from 'moment';
import { buildQuery } from 'postgres-typescript';

export interface Arguments {
  rootPortCallId: string;
  newEta: Moment;
  newEtd: Moment;
  newIsDeleted: boolean;
  userId: string;
  scenarioId: string;
  editMethod: string;
}

export interface Result {
  
}

export const data3 = buildQuery<Arguments, Result>(__filename);