-- @arg name:string
-- @arg def:../DataTypeTest1
-- @arg user:../../DataTypeTest2{User}
-- @arg def2:../../DataTypeTest2
-- @arg ids:number[]
-- @arg bool:boolean
-- @arg date:moment{Moment}
-- @return ../../DataTypeTest2
-- @return user:../../DataTypeTest2{User}
-- @return portCalls:../../DataTypeTest2{PortCall[]}
SELECT * FROM dummy